# every state, reason and dependency label the evaluator can emit lives here

# neutral phenotype category codes the adapter must use for binary results
CATEGORY_SUSCEPTIBLE = "S"
CATEGORY_RESISTANT = "R"

# phenotype stage outputs
PHENOTYPE_S = "PHENOTYPE_S"
PHENOTYPE_R = "PHENOTYPE_R"
PHENOTYPE_UNRESOLVED_NONBINARY = "PHENOTYPE_UNRESOLVED_NONBINARY"
PHENOTYPE_CONFLICT = "PHENOTYPE_CONFLICT"
PHENOTYPE_MISSING = "PHENOTYPE_MISSING"

# genotype stage outputs
GENOTYPE_DECISIVE_SUPPORT = "GENOTYPE_DECISIVE_SUPPORT"
GENOTYPE_CONTEXTUAL_SUPPORT = "GENOTYPE_CONTEXTUAL_SUPPORT"
GENOTYPE_NO_MAPPED_SUPPORT = "GENOTYPE_NO_MAPPED_SUPPORT"
GENOTYPE_INVALID_ANALYSIS = "GENOTYPE_INVALID_ANALYSIS"

GENOTYPE_STATES = frozenset(
    {
        GENOTYPE_DECISIVE_SUPPORT,
        GENOTYPE_CONTEXTUAL_SUPPORT,
        GENOTYPE_NO_MAPPED_SUPPORT,
        GENOTYPE_INVALID_ANALYSIS,
    }
)

# the five case states
CONCORDANT_RESISTANT = "CONCORDANT_RESISTANT"
CONCORDANT_SUSCEPTIBLE = "CONCORDANT_SUSCEPTIBLE"
DISCORDANT_GENOTYPE_POSITIVE_PHENOTYPE_S = "DISCORDANT_GENOTYPE_POSITIVE_PHENOTYPE_S"
DISCORDANT_PHENOTYPE_R_NO_MAPPED_GENOTYPE = "DISCORDANT_PHENOTYPE_R_NO_MAPPED_GENOTYPE"
UNRESOLVED = "UNRESOLVED"

# why a case ended up unresolved
REASON_NONBINARY_PHENOTYPE = "NONBINARY_PHENOTYPE"
REASON_PHENOTYPE_CONFLICT = "PHENOTYPE_CONFLICT"
REASON_MISSING_PHENOTYPE = "MISSING_PHENOTYPE"
REASON_INVALID_GENOTYPE_ANALYSIS = "INVALID_GENOTYPE_ANALYSIS"
REASON_CONTEXTUAL_GENOTYPE_EVIDENCE = "CONTEXTUAL_GENOTYPE_EVIDENCE"

# dependency vocabulary shared with the materializer
DEP_INPUT_EVIDENCE = "input_evidence"
DEP_POSITIVE_SUPPORT = "positive_support"
DEP_APPLICABILITY = "applicability"
DEP_PROVENANCE_VERSION = "provenance_version"

EDGE_DERIVED_FROM = "derived_from"
EDGE_EVALUATED_AGAINST = "evaluated_against"

NODE_AST_EVIDENCE = "ast_evidence"
NODE_GENOTYPE_EVIDENCE = "genotype_evidence"
NODE_MAPPING_RULE = "mapping_rule"
